version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: cab
          POSTGRES_DB: cab
          POSTGRES_PASSWORD: 12345678
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r cab_booking/requirements.txt

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python cab_booking/manage.py test

workflows:
  version: 2
  test:
    jobs:
      - test
