version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9  # Ensure the image has Python 3.9
    working_directory: ~/repo

jobs:
  build_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r cab_booking/requirements.txt
      - run:
          name: Build Docker image
          command: docker build -t myapp:${CIRCLE_SHA1} .

  push_image_to_ecr:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Authenticate with ECR
          command: |
            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
      - run:
          name: Push Docker image to ECR
          command: |
            docker tag myapp:${CIRCLE_SHA1} ${AWS_ECR_ACCOUNT_URL}/myapp:${CIRCLE_SHA1}
            docker push ${AWS_ECR_ACCOUNT_URL}/myapp:${CIRCLE_SHA1}

  deploy_to_ec2:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Deploy to EC2
          command: |
            aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_image
      - push_image_to_ecr:
          requires:
            - build_image
      - deploy_to_ec2:
          requires:
            - push_image_to_ecr
